
# GitHub Actions Example (.github/workflows/deploy.yml)
name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t user-service .
    - name: Push to Registry
      run: docker tag user-service ghcr.io/yourrepo/user-service:latest

